version: "3.7"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: nht123
      MYSQL_DATABASE: phonebook
      MYSQL_USER: admin
      MYSQL_PASSWORD: nihat1234
    networks:
      - phonebook
  myapp:
    build: .
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - phonebook
  
networks:
  phonebook:
    driver: bridge